development:
  secret_key_base: 3b7cd727ee24e8444053437c36cc66c3
  google_client_id: 780656768882-p7d0btiutbtdpdr658cftc7t6ll8q368.apps.googleusercontent.com
  google_client_secret: YQQsVHK5tVz--S3aHsQNhxHn